#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytools
Version  : 2020.4
Release  : 17
URL      : https://files.pythonhosted.org/packages/73/d5/989a1d2bba90f5c085e4929a4b703bbd8cc6b4a4218f1671fadab2abe966/pytools-2020.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/73/d5/989a1d2bba90f5c085e4929a4b703bbd8cc6b4a4218f1671fadab2abe966/pytools-2020.4.tar.gz
Summary  : A collection of tools for Python
Group    : Development/Tools
License  : MIT
Requires: pytools-license = %{version}-%{release}
Requires: pytools-python = %{version}-%{release}
Requires: pytools-python3 = %{version}-%{release}
Requires: appdirs
Requires: decorator
Requires: numpy
Requires: six
BuildRequires : appdirs
BuildRequires : buildreq-distutils3
BuildRequires : decorator
BuildRequires : numpy
BuildRequires : six

%description
=================================

%package license
Summary: license components for the pytools package.
Group: Default

%description license
license components for the pytools package.


%package python
Summary: python components for the pytools package.
Group: Default
Requires: pytools-python3 = %{version}-%{release}

%description python
python components for the pytools package.


%package python3
Summary: python3 components for the pytools package.
Group: Default
Requires: python3-core
Provides: pypi(pytools)
Requires: pypi(appdirs)
Requires: pypi(decorator)
Requires: pypi(numpy)
Requires: pypi(six)

%description python3
python3 components for the pytools package.


%prep
%setup -q -n pytools-2020.4
cd %{_builddir}/pytools-2020.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1597260925
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytools
cp %{_builddir}/pytools-2020.4/LICENSE %{buildroot}/usr/share/package-licenses/pytools/fe31187aa5e1860dd6a99af907678c3036474ada
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytools/fe31187aa5e1860dd6a99af907678c3036474ada

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
