#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytools
Version  : 2020.1
Release  : 11
URL      : https://files.pythonhosted.org/packages/66/c7/88a4f8b6f0f78d0115ec3320861a0cc1f6daa3b67e97c3c2842c33f9c089/pytools-2020.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/66/c7/88a4f8b6f0f78d0115ec3320861a0cc1f6daa3b67e97c3c2842c33f9c089/pytools-2020.1.tar.gz
Summary  : A collection of tools for Python
Group    : Development/Tools
License  : MIT
Requires: pytools-license = %{version}-%{release}
Requires: pytools-python = %{version}-%{release}
Requires: pytools-python3 = %{version}-%{release}
Requires: appdirs
Requires: decorator
Requires: numpy
Requires: six
BuildRequires : appdirs
BuildRequires : buildreq-distutils3
BuildRequires : decorator
BuildRequires : numpy
BuildRequires : six

%description
Pytools: Lots of Little Utilities
=================================
.. image:: https://gitlab.tiker.net/inducer/pytools/badges/master/pipeline.svg
:alt: Gitlab Build Status
:target: https://gitlab.tiker.net/inducer/pytools/commits/master
.. image:: https://dev.azure.com/ak-spam/inducer/_apis/build/status/inducer.pytools?branchName=master
:alt: Azure Build Status
:target: https://dev.azure.com/ak-spam/inducer/_build/latest?definitionId=2&branchName=master
.. image:: https://badge.fury.io/py/pytools.png
:alt: Python Package Index Release Page
:target: https://pypi.org/project/pytools/

%package license
Summary: license components for the pytools package.
Group: Default

%description license
license components for the pytools package.


%package python
Summary: python components for the pytools package.
Group: Default
Requires: pytools-python3 = %{version}-%{release}

%description python
python components for the pytools package.


%package python3
Summary: python3 components for the pytools package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytools package.


%prep
%setup -q -n pytools-2020.1
cd %{_builddir}/pytools-2020.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579111018
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytools
cp %{_builddir}/pytools-2020.1/LICENSE %{buildroot}/usr/share/package-licenses/pytools/fe31187aa5e1860dd6a99af907678c3036474ada
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytools/fe31187aa5e1860dd6a99af907678c3036474ada

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
